# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField()),
                ('enter_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garageAutomation.Account')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=6)),
                ('card_number', models.CharField(max_length=16)),
                ('exp', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garageAutomation.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('make', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garageAutomation.Account')),
            ],
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='paymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garageAutomation.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garageAutomation.Vehicle'),
        ),
    ]
