# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageAutomation', '0002_auto_20170324_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
