# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageAutomation', '0003_auto_20170324_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
