# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garageAutomation', '0005_auto_20170324_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='enter_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='enter time'),
        ),
    ]
