# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garageAutomation', '0006_auto_20170325_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingsession',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='parkingsession',
            name='enter_time',
        ),
    ]
