# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garageAutomation', '0007_auto_20170325_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='enter_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 25, 20, 2, 8, 46648, tzinfo=utc)),
        ),
    ]
