# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:51
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('max_levels', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[1-9]\\d{0,2}$')])),
                ('max_spots', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[1-9]\\d{0,4}$')])),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Credit_Card', models.CharField(blank=True, max_length=16)),
                ('license_plate_number', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{6,7}$')])),
                ('time_arrived', models.CharField(blank=True, max_length=10)),
                ('time_exited', models.CharField(blank=True, max_length=10)),
                ('stay_length', models.CharField(blank=True, max_length=2)),
                ('amount_charged', models.CharField(blank=True, max_length=5)),
                ('user_type', models.CharField(max_length=1)),
                ('parkingLot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parking.Parking_Lot')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.IntegerField(validators=[django.core.validators.RegexValidator('^[1-9]{0,10}$')])),
                ('sensor_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('level', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[1-9]{1,3}$')])),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('parkingLot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Parking_Lot')),
            ],
        ),
    ]
