# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_activesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='activesession',
            name='date_arrived',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='activesession',
            name='date_exited',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='date_arrived',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='date_exited',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
    ]
