# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20170423_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesession',
            name='date_arrived',
        ),
        migrations.RemoveField(
            model_name='activesession',
            name='date_exited',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date_arrived',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date_exited',
        ),
    ]
