# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20170317_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
