# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_spot_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
