# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garageAutomation', '__first__'),
        ('parking', '0005_auto_20170323_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasPaid', models.BooleanField(default=False)),
                ('user_type', models.CharField(default=3, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CC', models.CharField(max_length=16)),
                ('user_type', models.CharField(default=2, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default=1, max_length=1)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garageAutomation.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_arrived', models.CharField(max_length=5)),
                ('time_exited', models.CharField(max_length=5)),
                ('stay_length', models.CharField(max_length=2)),
                ('amount_charged', models.CharField(max_length=5)),
                ('user_type', models.CharField(max_length=1)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garageAutomation.Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='registereduser',
            name='reg_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.Session'),
        ),
        migrations.AddField(
            model_name='guestuser',
            name='guest_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.Session'),
        ),
        migrations.AddField(
            model_name='cashuser',
            name='cash_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.Session'),
        ),
    ]
