# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20170323_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='spot_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d[1-9]{1,10}$')]),
        ),
    ]
