# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20170324_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='session',
            name='license_plate_number',
            field=models.CharField(default='ABC123', max_length=7, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{6,7}$')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='amount_charged',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='session',
            name='stay_length',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_arrived',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_exited',
            field=models.CharField(default='', max_length=5),
        ),
    ]
