# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_auto_20170324_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='parkingLot',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='parking.Parking_Lot'),
            preserve_default=False,
        ),
    ]
