# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_session_parkinglot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='account',
        ),
    ]
