# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_auto_20170325_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='CreditCard',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
