# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_auto_20170325_1828'),
        ('parking', '0013_auto_20170325_1846'),
    ]

    operations = [
    ]
