# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_merge_20170326_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashuser',
            name='cash_user',
        ),
        migrations.RemoveField(
            model_name='guestuser',
            name='guest_user',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='reg_user',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='CreditCard',
            new_name='Credit_Card',
        ),
        migrations.DeleteModel(
            name='CashUser',
        ),
        migrations.DeleteModel(
            name='GuestUser',
        ),
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
    ]
