# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_auto_20170326_1659'),
        ('parking', '0014_merge_20170326_1840'),
        ('parking', '0015_auto_20170326_1958'),
    ]

    operations = [
    ]
