# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0016_merge_20170326_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='level',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d[1-9]{1,3}$')]),
        ),
    ]
